version: 2
updates:
  - package-ecosystem: github-actions
    target-branch: master
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci(deps)"
    labels:
      - dependencies
      - build
